Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.network "forwarded_port", guest: 5000, host: 5000
    config.vm.network "forwarded_port", guest: 5100, host: 5100
    config.vm.provider "virtualbox" do |vb|
        vb.name = "linux"
    end

    config.vm.provision "file", source: ".", destination: "~/Lab5"
    config.vm.provision "shell", privileged: false, inline: <<~SCRIPT
        wget https://download.visualstudio.microsoft.com/download/pr/5226a5fa-8c0b-474f-b79a-8984ad7c5beb/3113ccbf789c9fd29972835f0f334b7a/dotnet-sdk-8.0.100-linux-x64.tar.gz -O dotnet.tar.gz
        mkdir dotnet
        tar zxf dotnet.tar.gz -C dotnet
        cat > .bashrc << EOL
        export DOTNET_ROOT=~/dotnet
        export PATH=\$PATH:~/dotnet
        EOL
    SCRIPT

    config.vm.provision "shell", privileged: false, run: "always", inline: <<~SCRIPT
        cd ~/Lab5/IdentityServer
        dotnet run --urls http://0.0.0.0:5000 &
        cd ~/Lab5/WebApplication
        dotnet run --urls http://0.0.0.0:5100 &
    SCRIPT
end